### ISSUE TITLE
UnicodeDecodeError running main.py on MacOS

### ISSUE THREAD

**Issue by gamuniz** [lucas-benedito/sos-ansible#2]
```

Traceback (most recent call last):
  File "/Users/user/devel/sos-ansible/sos-ansible/main.py", line 107, in <module>
    main()
  File "/Users/user/devel/sos-ansible/sos-ansible/main.py", line 103, in main
    rules_processing(node_data, curr_policy, user_choice)
  File "/Users/gmuniz/devel/sos-ansible/sos-ansible/main.py", line 55, in rules_processing
    match_count = process_rule(hostname, user_choice, rules, to_read, query)
  File "/Users/user/devel/sos-ansible/sos-ansible/modules/file_handling.py", line 75, in process_rule
    for lines in file.readlines():
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 7042: invalid start byte

```

**Comment by lucas-benedito** [comment]
@gamuniz ive been unable to reproduce this error. Can you share a sample file that would trigger this error?

**Comment by gamuniz** [comment]
closing this after merging some fixes
